# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fromwin7.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Formwin7(object):
    def setupUi(self, Formwin7):
        Formwin7.setObjectName("Formwin7")
        Formwin7.resize(571, 388)
        self.label_daichuli = QtWidgets.QLabel(Formwin7)
        self.label_daichuli.setGeometry(QtCore.QRect(70, 40, 201, 201))
        self.label_daichuli.setObjectName("label_daichuli")
        self.label_jieguo = QtWidgets.QLabel(Formwin7)
        self.label_jieguo.setGeometry(QtCore.QRect(300, 40, 201, 201))
        self.label_jieguo.setObjectName("label_jieguo")
        self.pushButton_load = QtWidgets.QPushButton(Formwin7)
        self.pushButton_load.setGeometry(QtCore.QRect(100, 260, 101, 31))
        self.pushButton_load.setObjectName("pushButton_load")
        self.pushButton_save = QtWidgets.QPushButton(Formwin7)
        self.pushButton_save.setGeometry(QtCore.QRect(350, 260, 101, 31))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_xiufu = QtWidgets.QPushButton(Formwin7)
        self.pushButton_xiufu.setGeometry(QtCore.QRect(230, 320, 101, 31))
        self.pushButton_xiufu.setObjectName("pushButton_xiufu")

        self.retranslateUi(Formwin7)
        QtCore.QMetaObject.connectSlotsByName(Formwin7)

    def retranslateUi(self, Formwin7):
        _translate = QtCore.QCoreApplication.translate
        Formwin7.setWindowTitle(_translate("Formwin7", "Form"))
        self.label_daichuli.setText(_translate("Formwin7", "待处理"))
        self.label_jieguo.setText(_translate("Formwin7", "结果"))
        self.pushButton_load.setText(_translate("Formwin7", "选择图片"))
        self.pushButton_save.setText(_translate("Formwin7", "保存图片"))
        self.pushButton_xiufu.setText(_translate("Formwin7", "图像修复"))
