# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fromwin4.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Formwin4(object):
    def setupUi(self, Formwin4):
        Formwin4.setObjectName("Formwin4")
        Formwin4.resize(571, 388)
        self.label_daichuli = QtWidgets.QLabel(Formwin4)
        self.label_daichuli.setGeometry(QtCore.QRect(80, 50, 151, 151))
        self.label_daichuli.setObjectName("label_daichuli")
        self.label_jieguo = QtWidgets.QLabel(Formwin4)
        self.label_jieguo.setGeometry(QtCore.QRect(340, 50, 151, 151))
        self.label_jieguo.setObjectName("label_jieguo")
        self.pushButton_load = QtWidgets.QPushButton(Formwin4)
        self.pushButton_load.setGeometry(QtCore.QRect(100, 220, 101, 31))
        self.pushButton_load.setObjectName("pushButton_load")
        self.pushButton_save = QtWidgets.QPushButton(Formwin4)
        self.pushButton_save.setGeometry(QtCore.QRect(350, 220, 101, 31))
        self.pushButton_save.setObjectName("pushButton_save")
        self.label_tips = QtWidgets.QLabel(Formwin4)
        self.label_tips.setGeometry(QtCore.QRect(10, 250, 41, 41))
        self.label_tips.setObjectName("label_tips")
        self.pushButton_zhifangtu = QtWidgets.QPushButton(Formwin4)
        self.pushButton_zhifangtu.setGeometry(QtCore.QRect(340, 280, 101, 31))
        self.pushButton_zhifangtu.setObjectName("pushButton_zhifangtu")
        self.pushButton_gama = QtWidgets.QPushButton(Formwin4)
        self.pushButton_gama.setGeometry(QtCore.QRect(340, 330, 101, 31))
        self.pushButton_gama.setObjectName("pushButton_gama")
        self.label = QtWidgets.QLabel(Formwin4)
        self.label.setGeometry(QtCore.QRect(160, 330, 21, 31))
        self.label.setObjectName("label")
        self.lineEdit_n_value = QtWidgets.QLineEdit(Formwin4)
        self.lineEdit_n_value.setGeometry(QtCore.QRect(180, 330, 101, 31))
        self.lineEdit_n_value.setObjectName("lineEdit_n_value")
        self.label_2 = QtWidgets.QLabel(Formwin4)
        self.label_2.setGeometry(QtCore.QRect(200, 360, 71, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Formwin4)
        self.label_3.setGeometry(QtCore.QRect(100, 280, 31, 31))
        self.label_3.setObjectName("label_3")
        self.lineEdit_mean_value = QtWidgets.QLineEdit(Formwin4)
        self.lineEdit_mean_value.setGeometry(QtCore.QRect(140, 280, 41, 31))
        self.lineEdit_mean_value.setObjectName("lineEdit_mean_value")
        self.lineEdit_val_value = QtWidgets.QLineEdit(Formwin4)
        self.lineEdit_val_value.setGeometry(QtCore.QRect(250, 280, 41, 31))
        self.lineEdit_val_value.setObjectName("lineEdit_val_value")
        self.label_4 = QtWidgets.QLabel(Formwin4)
        self.label_4.setGeometry(QtCore.QRect(220, 280, 31, 31))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Formwin4)
        QtCore.QMetaObject.connectSlotsByName(Formwin4)

    def retranslateUi(self, Formwin4):
        _translate = QtCore.QCoreApplication.translate
        Formwin4.setWindowTitle(_translate("Formwin4", "Form"))
        self.label_daichuli.setText(_translate("Formwin4", "待处理"))
        self.label_jieguo.setText(_translate("Formwin4", "结果"))
        self.pushButton_load.setText(_translate("Formwin4", "选择图片"))
        self.pushButton_save.setText(_translate("Formwin4", "保存图片"))
        self.label_tips.setText(_translate("Formwin4", "操作："))
        self.pushButton_zhifangtu.setText(_translate("Formwin4", "添加高斯噪声"))
        self.pushButton_gama.setText(_translate("Formwin4", "添加椒盐噪声"))
        self.label.setText(_translate("Formwin4", "n="))
        self.lineEdit_n_value.setText(_translate("Formwin4", "1000"))
        self.label_2.setText(_translate("Formwin4", "(注：个数)"))
        self.label_3.setText(_translate("Formwin4", "mean="))
        self.lineEdit_mean_value.setText(_translate("Formwin4", "0"))
        self.lineEdit_val_value.setText(_translate("Formwin4", "0.01"))
        self.label_4.setText(_translate("Formwin4", "val="))
