# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fromwin3.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Formwin3(object):
    def setupUi(self, Formwin3):
        Formwin3.setObjectName("Formwin3")
        Formwin3.resize(571, 388)
        self.label_daichuli = QtWidgets.QLabel(Formwin3)
        self.label_daichuli.setGeometry(QtCore.QRect(80, 50, 151, 151))
        self.label_daichuli.setObjectName("label_daichuli")
        self.label_jieguo = QtWidgets.QLabel(Formwin3)
        self.label_jieguo.setGeometry(QtCore.QRect(340, 50, 151, 151))
        self.label_jieguo.setObjectName("label_jieguo")
        self.pushButton_load = QtWidgets.QPushButton(Formwin3)
        self.pushButton_load.setGeometry(QtCore.QRect(100, 220, 101, 31))
        self.pushButton_load.setObjectName("pushButton_load")
        self.pushButton_save = QtWidgets.QPushButton(Formwin3)
        self.pushButton_save.setGeometry(QtCore.QRect(350, 220, 101, 31))
        self.pushButton_save.setObjectName("pushButton_save")
        self.label_tips = QtWidgets.QLabel(Formwin3)
        self.label_tips.setGeometry(QtCore.QRect(40, 280, 51, 41))
        self.label_tips.setObjectName("label_tips")
        self.pushButton_lap = QtWidgets.QPushButton(Formwin3)
        self.pushButton_lap.setGeometry(QtCore.QRect(160, 290, 101, 31))
        self.pushButton_lap.setObjectName("pushButton_lap")
        self.pushButton_zhifangtu = QtWidgets.QPushButton(Formwin3)
        self.pushButton_zhifangtu.setGeometry(QtCore.QRect(290, 290, 101, 31))
        self.pushButton_zhifangtu.setObjectName("pushButton_zhifangtu")
        self.pushButton_gama = QtWidgets.QPushButton(Formwin3)
        self.pushButton_gama.setGeometry(QtCore.QRect(290, 340, 101, 31))
        self.pushButton_gama.setObjectName("pushButton_gama")
        self.label = QtWidgets.QLabel(Formwin3)
        self.label.setGeometry(QtCore.QRect(80, 340, 51, 31))
        self.label.setObjectName("label")
        self.lineEdit_power_value = QtWidgets.QLineEdit(Formwin3)
        self.lineEdit_power_value.setGeometry(QtCore.QRect(150, 340, 111, 31))
        self.lineEdit_power_value.setObjectName("lineEdit_power_value")

        self.retranslateUi(Formwin3)
        QtCore.QMetaObject.connectSlotsByName(Formwin3)

    def retranslateUi(self, Formwin3):
        _translate = QtCore.QCoreApplication.translate
        Formwin3.setWindowTitle(_translate("Formwin3", "Form"))
        self.label_daichuli.setText(_translate("Formwin3", "待处理"))
        self.label_jieguo.setText(_translate("Formwin3", "结果"))
        self.pushButton_load.setText(_translate("Formwin3", "选择图片"))
        self.pushButton_save.setText(_translate("Formwin3", "保存图片"))
        self.label_tips.setText(_translate("Formwin3", "操作："))
        self.pushButton_lap.setText(_translate("Formwin3", "拉普拉斯变化"))
        self.pushButton_zhifangtu.setText(_translate("Formwin3", "直方图均衡"))
        self.pushButton_gama.setText(_translate("Formwin3", "伽马变化"))
        self.label.setText(_translate("Formwin3", "power1="))
        self.lineEdit_power_value.setText(_translate("Formwin3", "1.5"))
from PyQt5.QtWidgets import QApplication, QMainWindow
import sys
# ... 省略你的所有TableWidget子类的定义 ...

def main():
    # 创建Qt应用程序对象
    app = QApplication(sys.argv)

    # 创建主窗口
    MainWindow = QMainWindow()
    ui = Ui_Formwin3()
    ui.setupUi(MainWindow)

    # 显示主窗口
    MainWindow.show()

    # 运行应用程序
    sys.exit(app.exec_())

if __name__ == "__main__":
    main()