# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fromwin1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Formwin1(object):
    def setupUi(self, Formwin1):
        Formwin1.setObjectName("Formwin1")
        Formwin1.resize(571, 388)
        self.label_daichuli = QtWidgets.QLabel(Formwin1)
        self.label_daichuli.setGeometry(QtCore.QRect(80, 50, 151, 151))
        self.label_daichuli.setObjectName("label_daichuli")
        self.label_jieguo = QtWidgets.QLabel(Formwin1)
        self.label_jieguo.setGeometry(QtCore.QRect(340, 50, 151, 151))
        self.label_jieguo.setObjectName("label_jieguo")
        self.pushButton_load = QtWidgets.QPushButton(Formwin1)
        self.pushButton_load.setGeometry(QtCore.QRect(100, 220, 101, 31))
        self.pushButton_load.setObjectName("pushButton_load")
        self.pushButton_save = QtWidgets.QPushButton(Formwin1)
        self.pushButton_save.setGeometry(QtCore.QRect(350, 220, 101, 31))
        self.pushButton_save.setObjectName("pushButton_save")
        self.label_tips = QtWidgets.QLabel(Formwin1)
        self.label_tips.setGeometry(QtCore.QRect(30, 280, 51, 41))
        self.label_tips.setObjectName("label_tips")
        self.pushButton_turntoGray = QtWidgets.QPushButton(Formwin1)
        self.pushButton_turntoGray.setGeometry(QtCore.QRect(120, 290, 101, 31))
        self.pushButton_turntoGray.setObjectName("pushButton_turntoGray")
        self.pushButton_turntotwo = QtWidgets.QPushButton(Formwin1)
        self.pushButton_turntotwo.setGeometry(QtCore.QRect(270, 290, 101, 31))
        self.pushButton_turntotwo.setObjectName("pushButton_turntotwo")

        self.retranslateUi(Formwin1)
        QtCore.QMetaObject.connectSlotsByName(Formwin1)

    def retranslateUi(self, Formwin1):
        _translate = QtCore.QCoreApplication.translate
        Formwin1.setWindowTitle(_translate("Formwin1", "Form"))
        self.label_daichuli.setText(_translate("Formwin1", "待处理"))
        self.label_jieguo.setText(_translate("Formwin1", "结果"))
        self.pushButton_load.setText(_translate("Formwin1", "选择图片"))
        self.pushButton_save.setText(_translate("Formwin1", "保存图片"))
        self.label_tips.setText(_translate("Formwin1", "操作："))
        self.pushButton_turntoGray.setText(_translate("Formwin1", "转成灰度图"))
        self.pushButton_turntotwo.setText(_translate("Formwin1", "将图片二值化"))
from PyQt5.QtWidgets import QApplication, QMainWindow
import sys
# ... 省略你的所有TableWidget子类的定义 ...

def main():
    # 创建Qt应用程序对象
    app = QApplication(sys.argv)

    # 创建主窗口
    MainWindow = QMainWindow()
    ui = Ui_Formwin1()
    ui.setupUi(MainWindow)

    # 显示主窗口
    MainWindow.show()

    # 运行应用程序
    sys.exit(app.exec_())

if __name__ == "__main__":
    main()