# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fromwin6.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Formwin6(object):
    def setupUi(self, Formwin6):
        Formwin6.setObjectName("Formwin6")
        Formwin6.resize(571, 388)
        self.label_daichuli = QtWidgets.QLabel(Formwin6)
        self.label_daichuli.setGeometry(QtCore.QRect(70, 40, 201, 201))
        self.label_daichuli.setObjectName("label_daichuli")
        self.label_jieguo = QtWidgets.QLabel(Formwin6)
        self.label_jieguo.setGeometry(QtCore.QRect(300, 40, 201, 201))
        self.label_jieguo.setObjectName("label_jieguo")
        self.pushButton_load = QtWidgets.QPushButton(Formwin6)
        self.pushButton_load.setGeometry(QtCore.QRect(100, 260, 101, 31))
        self.pushButton_load.setObjectName("pushButton_load")
        self.pushButton_save = QtWidgets.QPushButton(Formwin6)
        self.pushButton_save.setGeometry(QtCore.QRect(350, 260, 101, 31))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_sift = QtWidgets.QPushButton(Formwin6)
        self.pushButton_sift.setGeometry(QtCore.QRect(100, 320, 101, 31))
        self.pushButton_sift.setObjectName("pushButton_sift")
        self.pushButton_lunkuo = QtWidgets.QPushButton(Formwin6)
        self.pushButton_lunkuo.setGeometry(QtCore.QRect(230, 320, 101, 31))
        self.pushButton_lunkuo.setObjectName("pushButton_lunkuo")

        self.retranslateUi(Formwin6)
        QtCore.QMetaObject.connectSlotsByName(Formwin6)

    def retranslateUi(self, Formwin6):
        _translate = QtCore.QCoreApplication.translate
        Formwin6.setWindowTitle(_translate("Formwin6", "Form"))
        self.label_daichuli.setText(_translate("Formwin6", "待处理"))
        self.label_jieguo.setText(_translate("Formwin6", "结果"))
        self.pushButton_load.setText(_translate("Formwin6", "选择图片"))
        self.pushButton_save.setText(_translate("Formwin6", "保存图片"))
        self.pushButton_sift.setText(_translate("Formwin6", "sift检测"))
        self.pushButton_lunkuo.setText(_translate("Formwin6", "轮廓检测"))
